

TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no

TAPPING_TERM = 250
BLINK_RATE = 500
AUTOREPEAT_RATE = 125

CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
AUTO_SHIFT_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE =yes		# requires 1800 bytes
#---
GET_AUTO_SHIFT_REPEAT = no
GET_AUTO_REPEAT_PER_KEY = no

